const path = require('path');

const games = [
	{
		id: 0,
		name: 'Super Mario World',
		console: 'Super Nintendo',
		key: 'smw',
		romUrl: `game/smw`,
		imageUrl: 'image/smw',
		rank: 5,
	},
	{
		id: 1,
		name: 'Super Bomber Man',
		console: 'Super Nintendo',
		key: 'sbm1',
		romUrl: `game/sbm1`,
		imageUrl: 'image/sbm1',
		rank: 0,
	},
	{
		id: 2,
		name: 'Super Bomber Man 2',
		console: 'Super Nintendo',
		key: 'sbm2',
		romUrl: `game/sbm2`,
		imageUrl: 'image/sbm2',
		rank: 0,
	},
	{
		id: 3,
		name: 'Super Bomber Man 3',
		console: 'Super Nintendo',
		key: 'sbm3',
		romUrl: `game/sbm3`,
		imageUrl: 'image/sbm3',
		rank: 0,
	},
	{
		id: 4,
		name: 'Super Bomber Man 4',
		console: 'Super Nintendo',
		key: 'sbm4',
		romUrl: `game/sbm4`,
		imageUrl: 'image/sbm4',
		rank: 0,
	},
	{
		id: 5,
		name: 'Super Bomber Man 5',
		console: 'Super Nintendo',
		key: 'sbm5',
		romUrl: `game/sbm5`,
		imageUrl: 'image/sbm5',
		rank: 5,
	},
	{
		id: 6,
		name: 'Donkey Kong',
		console: 'Super Nintendo',
		key: 'dkg',
		romUrl: `game/dkg`,
		imageUrl: 'image/sbm5',
		rank: 5,
	},
	{
		id: 7,
		name: 'Donkey Kong 2',
		console: 'Super Nintendo',
		key: 'dkg2',
		romUrl: `game/dkg2`,
		imageUrl: 'image/sbm5',
		rank: 0,
	},
	{
		id: 8,
		name: 'Donkey Kong 3',
		console: 'Super Nintendo',
		key: 'dkg3',
		romUrl: `game/dkg3`,
		imageUrl: 'image/sbm5',
		rank: 0,
	},
	{
		id: 9,
		name: 'Zelda',
		console: 'Super Nintendo',
		key: 'zelda',
		romUrl: `game/zelda`,
		imageUrl: 'image/sbm5',
		rank: 5,
	},
	{
		id: 10,
		name: 'Super Mario Kart',
		console: 'Super Nintendo',
		key: 'smk',
		romUrl: `game/smk`,
		imageUrl: 'image/smk',
		rank: 5,
	},
	{
		id: 11,
		name: 'Dragon Ball Z',
		console: 'Super Nintendo',
		key: 'dbz',
		romUrl: `game/dbz`,
		imageUrl: 'image/dbz',
		rank: 5,
	},
];

module.exports = games;
